default_parms = {
    'n_harvest': 400,
    'washout': 500,
    'learning_rate_c': 0.5,
    'beta_W_out': 0.01,
    'beta_G': 1,
    'beta_D': 0.01,
    'aperture': 8,
    'spectral_radius': 1.4,
    'N': 100,
    'M': 500,
    'n_adapt': 2000,
    'W_sr': 1.5,
    'W_sparseness': 0.1,
    'd_dim': "reservoir_dim",
    'F_method': "patterns",
    'signal_dim': 1,
    'G_method': "W_F",
    'noise_mean':None,
    'noise_std':None,
}